export {
  aiGenerateEmailTemplateSchema,
  createDomainSchema,
  createProviderSchema,
  createSenderSchema,
  listLogsSchema,
  sendEmailSchema,
  sesCredentialsDraftSchema,
  setDefaultSenderSchema,
  updateEmailTemplateSchema,
  updateProviderSchema,
  upsertEmailTemplateSchema,
  verifyDomainSchema,
} from '../email.schemas.js';
export type {
  CreateDomainDto,
  CreateProviderDto,
  CreateSenderDto,
  ListLogsDto,
  SendEmailDto,
  SesCredentialsDraftDto,
  UpdateEmailTemplateDto,
  UpdateProviderDto,
  UpsertEmailTemplateDto,
  VerifyDomainDto,
} from '../email.schemas.js';
