-- AlterTable
ALTER TABLE "SocialComment" ADD COLUMN IF NOT EXISTS "publicReplyText" TEXT;
ALTER TABLE "SocialComment" ADD COLUMN IF NOT EXISTS "dmReplyText" TEXT;
ALTER TABLE "SocialComment" ADD COLUMN IF NOT EXISTS "dmSentAt" TIMESTAMP(3);
ALTER TABLE "SocialComment" ADD COLUMN IF NOT EXISTS "dmStatus" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "SocialComment" ADD COLUMN IF NOT EXISTS "dmError" TEXT;
