/** Extensible in-app notification / activity type constants (not DB enums). */
export const NOTIFICATION_TYPES = {
  // Alert-worthy (bell by default)
  TEMPLATE_APPROVED: 'template_approved',
  TEMPLATE_REJECTED: 'template_rejected',
  CAMPAIGN_COMPLETED: 'campaign_completed',
  CAMPAIGN_FAILED: 'campaign_failed',
  CONTACT_IMPORT_FINISHED: 'contact_import_finished',
  WALLET_BALANCE_LOW: 'wallet_balance_low',
  TEAM_MEMBER_ADDED: 'team_member_added',

  // User activity (route hook) — activity feed; forBell=false by default
  USER_ACTION: 'user_action',
  CAMPAIGN_CREATED: 'campaign_created',
  CAMPAIGN_UPDATED: 'campaign_updated',
  CAMPAIGN_SEND: 'campaign_send',
  CAMPAIGN_RESEND: 'campaign_resend',
  TEMPLATE_CREATED: 'template_created',
  TEMPLATE_UPDATED: 'template_updated',
  TEMPLATE_DELETED: 'template_deleted',
  TEMPLATE_SUBMITTED: 'template_submitted',
  TEMPLATE_SYNCED: 'template_synced',
  CONTACT_CREATED: 'contact_created',
  CONTACT_UPDATED: 'contact_updated',
  CONTACT_DELETED: 'contact_deleted',
  CONTACT_TAGGED: 'contact_tagged',
  INBOX_MESSAGE_SENT: 'inbox_message_sent',
  INBOX_CONVERSATION_UPDATED: 'inbox_conversation_updated',
  INBOX_TAKEOVER: 'inbox_takeover',
  INBOX_RELEASE_AI: 'inbox_release_ai',
  TEAM_CHAT_MESSAGE: 'team_chat_message',
  JOURNEY_CREATED: 'journey_created',
  JOURNEY_UPDATED: 'journey_updated',
  JOURNEY_PUBLISHED: 'journey_published',
  JOURNEY_DELETED: 'journey_deleted',
  AGENT_CREATED: 'agent_created',
  AGENT_UPDATED: 'agent_updated',
  AGENT_TOGGLED: 'agent_toggled',
  AGENT_DELETED: 'agent_deleted',
  LEAD_CREATED: 'lead_created',
  LEAD_UPDATED: 'lead_updated',
  LEAD_CONVERTED: 'lead_converted',
  MEDIA_UPLOADED: 'media_uploaded',
  MEDIA_DELETED: 'media_deleted',
  INTEGRATION_CONNECTED: 'integration_connected',
  INTEGRATION_DISCONNECTED: 'integration_disconnected',
  WALLET_TOPUP: 'wallet_topup',
  SETTINGS_UPDATED: 'settings_updated',
  TEAM_MEMBER_UPDATED: 'team_member_updated',
  TEAM_MEMBER_REMOVED: 'team_member_removed',
  SOCIAL_LISTENING_ACTION: 'social_listening_action',
  CALL_ACTION: 'call_action',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

/** Extensible category buckets for filter tabs + activity grouping. */
export const NOTIFICATION_CATEGORIES = {
  CAMPAIGNS: 'campaigns',
  SYSTEM: 'system',
  IMPORTS: 'imports',
  INBOX: 'inbox',
  CONTACTS: 'contacts',
  TEAM_CHAT: 'team_chat',
  TEMPLATES: 'templates',
  AUTOMATIONS: 'automations',
  AI_AGENT: 'ai_agent',
  SOCIAL_LISTENING: 'social_listening',
  LEADS: 'leads',
  MEDIA: 'media',
  INTEGRATIONS: 'integrations',
  WALLET: 'wallet',
  SETTINGS: 'settings',
  CALLING: 'calling',
  DEVELOPERS: 'developers',
} as const;

export type NotificationCategory =
  (typeof NOTIFICATION_CATEGORIES)[keyof typeof NOTIFICATION_CATEGORIES];

export type NotificationSeverity = 'success' | 'failure' | 'info' | 'warning';

const TYPE_CATEGORY: Record<string, NotificationCategory> = {
  [NOTIFICATION_TYPES.TEMPLATE_APPROVED]: NOTIFICATION_CATEGORIES.TEMPLATES,
  [NOTIFICATION_TYPES.TEMPLATE_REJECTED]: NOTIFICATION_CATEGORIES.TEMPLATES,
  [NOTIFICATION_TYPES.CAMPAIGN_COMPLETED]: NOTIFICATION_CATEGORIES.CAMPAIGNS,
  [NOTIFICATION_TYPES.CAMPAIGN_FAILED]: NOTIFICATION_CATEGORIES.CAMPAIGNS,
  [NOTIFICATION_TYPES.CONTACT_IMPORT_FINISHED]: NOTIFICATION_CATEGORIES.IMPORTS,
  [NOTIFICATION_TYPES.WALLET_BALANCE_LOW]: NOTIFICATION_CATEGORIES.WALLET,
  [NOTIFICATION_TYPES.TEAM_MEMBER_ADDED]: NOTIFICATION_CATEGORIES.SETTINGS,
  [NOTIFICATION_TYPES.CAMPAIGN_CREATED]: NOTIFICATION_CATEGORIES.CAMPAIGNS,
  [NOTIFICATION_TYPES.CAMPAIGN_UPDATED]: NOTIFICATION_CATEGORIES.CAMPAIGNS,
  [NOTIFICATION_TYPES.CAMPAIGN_SEND]: NOTIFICATION_CATEGORIES.CAMPAIGNS,
  [NOTIFICATION_TYPES.CAMPAIGN_RESEND]: NOTIFICATION_CATEGORIES.CAMPAIGNS,
  [NOTIFICATION_TYPES.TEMPLATE_CREATED]: NOTIFICATION_CATEGORIES.TEMPLATES,
  [NOTIFICATION_TYPES.TEMPLATE_UPDATED]: NOTIFICATION_CATEGORIES.TEMPLATES,
  [NOTIFICATION_TYPES.TEMPLATE_DELETED]: NOTIFICATION_CATEGORIES.TEMPLATES,
  [NOTIFICATION_TYPES.TEMPLATE_SUBMITTED]: NOTIFICATION_CATEGORIES.TEMPLATES,
  [NOTIFICATION_TYPES.TEMPLATE_SYNCED]: NOTIFICATION_CATEGORIES.TEMPLATES,
  [NOTIFICATION_TYPES.CONTACT_CREATED]: NOTIFICATION_CATEGORIES.CONTACTS,
  [NOTIFICATION_TYPES.CONTACT_UPDATED]: NOTIFICATION_CATEGORIES.CONTACTS,
  [NOTIFICATION_TYPES.CONTACT_DELETED]: NOTIFICATION_CATEGORIES.CONTACTS,
  [NOTIFICATION_TYPES.CONTACT_TAGGED]: NOTIFICATION_CATEGORIES.CONTACTS,
  [NOTIFICATION_TYPES.INBOX_MESSAGE_SENT]: NOTIFICATION_CATEGORIES.INBOX,
  [NOTIFICATION_TYPES.INBOX_CONVERSATION_UPDATED]: NOTIFICATION_CATEGORIES.INBOX,
  [NOTIFICATION_TYPES.INBOX_TAKEOVER]: NOTIFICATION_CATEGORIES.INBOX,
  [NOTIFICATION_TYPES.INBOX_RELEASE_AI]: NOTIFICATION_CATEGORIES.INBOX,
  [NOTIFICATION_TYPES.TEAM_CHAT_MESSAGE]: NOTIFICATION_CATEGORIES.TEAM_CHAT,
  [NOTIFICATION_TYPES.JOURNEY_CREATED]: NOTIFICATION_CATEGORIES.AUTOMATIONS,
  [NOTIFICATION_TYPES.JOURNEY_UPDATED]: NOTIFICATION_CATEGORIES.AUTOMATIONS,
  [NOTIFICATION_TYPES.JOURNEY_PUBLISHED]: NOTIFICATION_CATEGORIES.AUTOMATIONS,
  [NOTIFICATION_TYPES.JOURNEY_DELETED]: NOTIFICATION_CATEGORIES.AUTOMATIONS,
  [NOTIFICATION_TYPES.AGENT_CREATED]: NOTIFICATION_CATEGORIES.AI_AGENT,
  [NOTIFICATION_TYPES.AGENT_UPDATED]: NOTIFICATION_CATEGORIES.AI_AGENT,
  [NOTIFICATION_TYPES.AGENT_TOGGLED]: NOTIFICATION_CATEGORIES.AI_AGENT,
  [NOTIFICATION_TYPES.AGENT_DELETED]: NOTIFICATION_CATEGORIES.AI_AGENT,
  [NOTIFICATION_TYPES.LEAD_CREATED]: NOTIFICATION_CATEGORIES.LEADS,
  [NOTIFICATION_TYPES.LEAD_UPDATED]: NOTIFICATION_CATEGORIES.LEADS,
  [NOTIFICATION_TYPES.LEAD_CONVERTED]: NOTIFICATION_CATEGORIES.LEADS,
  [NOTIFICATION_TYPES.MEDIA_UPLOADED]: NOTIFICATION_CATEGORIES.MEDIA,
  [NOTIFICATION_TYPES.MEDIA_DELETED]: NOTIFICATION_CATEGORIES.MEDIA,
  [NOTIFICATION_TYPES.INTEGRATION_CONNECTED]: NOTIFICATION_CATEGORIES.INTEGRATIONS,
  [NOTIFICATION_TYPES.INTEGRATION_DISCONNECTED]: NOTIFICATION_CATEGORIES.INTEGRATIONS,
  [NOTIFICATION_TYPES.WALLET_TOPUP]: NOTIFICATION_CATEGORIES.WALLET,
  [NOTIFICATION_TYPES.SETTINGS_UPDATED]: NOTIFICATION_CATEGORIES.SETTINGS,
  [NOTIFICATION_TYPES.TEAM_MEMBER_UPDATED]: NOTIFICATION_CATEGORIES.SETTINGS,
  [NOTIFICATION_TYPES.TEAM_MEMBER_REMOVED]: NOTIFICATION_CATEGORIES.SETTINGS,
  [NOTIFICATION_TYPES.SOCIAL_LISTENING_ACTION]: NOTIFICATION_CATEGORIES.SOCIAL_LISTENING,
  [NOTIFICATION_TYPES.CALL_ACTION]: NOTIFICATION_CATEGORIES.CALLING,
  [NOTIFICATION_TYPES.USER_ACTION]: NOTIFICATION_CATEGORIES.SYSTEM,
};

const TYPE_SEVERITY: Record<string, NotificationSeverity> = {
  [NOTIFICATION_TYPES.TEMPLATE_APPROVED]: 'success',
  [NOTIFICATION_TYPES.TEMPLATE_REJECTED]: 'failure',
  [NOTIFICATION_TYPES.CAMPAIGN_COMPLETED]: 'success',
  [NOTIFICATION_TYPES.CAMPAIGN_FAILED]: 'failure',
  [NOTIFICATION_TYPES.CONTACT_IMPORT_FINISHED]: 'info',
  [NOTIFICATION_TYPES.WALLET_BALANCE_LOW]: 'warning',
  [NOTIFICATION_TYPES.TEAM_MEMBER_ADDED]: 'success',
  [NOTIFICATION_TYPES.CAMPAIGN_SEND]: 'success',
  [NOTIFICATION_TYPES.LEAD_CONVERTED]: 'success',
  [NOTIFICATION_TYPES.INTEGRATION_CONNECTED]: 'success',
  [NOTIFICATION_TYPES.WALLET_TOPUP]: 'success',
};

/** Types that should appear in the notifications bell by default. */
const BELL_TYPES = new Set<string>([
  NOTIFICATION_TYPES.TEMPLATE_APPROVED,
  NOTIFICATION_TYPES.TEMPLATE_REJECTED,
  NOTIFICATION_TYPES.CAMPAIGN_COMPLETED,
  NOTIFICATION_TYPES.CAMPAIGN_FAILED,
  NOTIFICATION_TYPES.CONTACT_IMPORT_FINISHED,
  NOTIFICATION_TYPES.WALLET_BALANCE_LOW,
  NOTIFICATION_TYPES.TEAM_MEMBER_ADDED,
]);

export function categoryForType(type: string): NotificationCategory {
  return TYPE_CATEGORY[type] ?? NOTIFICATION_CATEGORIES.SYSTEM;
}

export function severityForType(type: string): NotificationSeverity {
  return TYPE_SEVERITY[type] ?? 'info';
}

/** Default bell visibility when emit omits forBell. */
export function forBellForType(type: string): boolean {
  return BELL_TYPES.has(type);
}
