/**
 * Maps reference field names to likely MongoDB collection names.
 * Used by RecursiveResolverService — extend when new entity types appear.
 */
export const REFERENCE_FIELD_COLLECTION_HINTS: Record<string, readonly string[]> = {
  services: ['services', 'service', 'treatments', 'treatment', 'offerings'],
  service: ['services', 'service', 'treatments'],
  serviceIds: ['services', 'service', 'treatments'],
  serviceId: ['services', 'service', 'treatments'],
  staff: ['staff', 'employees', 'employee', 'stylists', 'team', 'team_members'],
  staffIds: ['staff', 'employees', 'employee', 'stylists', 'team'],
  staffId: ['staff', 'employees', 'employee', 'stylists'],
  employee: ['employees', 'employee', 'staff', 'stylists'],
  employeeIds: ['employees', 'employee', 'staff'],
  categories: ['categories', 'category', 'service_categories', 'serviceCategories', 'service_types'],
  category: ['categories', 'category', 'service_categories', 'serviceCategories'],
  categoryId: ['categories', 'category', 'service_categories', 'serviceCategories'],
  categoryIds: ['categories', 'category', 'service_categories'],
  memberships: ['memberships', 'membership', 'membership_plans', 'plans'],
  membership: ['memberships', 'membership', 'membership_plans'],
  membershipId: ['memberships', 'membership', 'membership_plans'],
  vouchers: ['vouchers', 'voucher', 'coupons', 'coupon', 'gift_cards', 'promo_codes'],
  voucher: ['vouchers', 'voucher', 'coupons', 'coupon'],
  voucherIds: ['vouchers', 'voucher', 'coupons'],
  products: ['products', 'product', 'inventory', 'retail_products'],
  product: ['products', 'product', 'inventory'],
  productIds: ['products', 'product', 'inventory'],
  packages: ['packages', 'package', 'bundles', 'combos', 'offers'],
  package: ['packages', 'package', 'bundles'],
  packageIds: ['packages', 'package', 'bundles'],
  branches: ['branches', 'branch', 'locations', 'location', 'stores'],
  branch: ['branches', 'branch', 'locations', 'location'],
  branchId: ['branches', 'branch', 'locations'],
  branchIds: ['branches', 'branch', 'locations'],
  settings: ['settings', 'business_settings', 'businessSettings', 'configurations', 'config'],
  setting: ['settings', 'business_settings', 'config'],
  settingsId: ['settings', 'business_settings', 'config'],
  faqs: ['faqs', 'faq', 'help_articles', 'questions'],
  faq: ['faqs', 'faq', 'help_articles'],
  policies: ['policies', 'policy', 'terms', 'terms_and_conditions', 'rules'],
  policy: ['policies', 'policy', 'terms'],
  customers: ['customers', 'customer', 'clients', 'client'],
  customer: ['customers', 'customer', 'clients', 'client'],
  customerId: ['customers', 'customer', 'clients'],
  customerIds: ['customers', 'customer', 'clients'],
  venue: ['venues', 'venue', 'salons', 'salon', 'businesses'],
  venueId: ['venues', 'venue', 'salons', 'salon'],
  salon: ['salons', 'salon', 'venues', 'venue', 'businesses'],
  salonId: ['salons', 'salon', 'venues', 'venue'],
};

/** Priority order when scanning DB for an unknown ObjectId reference. */
export const COLLECTION_SCAN_PRIORITY = [
  'services',
  'service',
  'staff',
  'employees',
  'categories',
  'category',
  'service_categories',
  'memberships',
  'membership',
  'packages',
  'package',
  'vouchers',
  'voucher',
  'products',
  'product',
  'branches',
  'branch',
  'settings',
  'faqs',
  'faq',
  'policies',
  'policy',
  'customers',
  'customer',
  'venues',
  'venue',
  'salons',
  'salon',
] as const;

export const RESOLVER_LIMITS = {
  maxDocuments: 2500,
  maxDepth: 12,
} as const;
